/* eslint-disable prettier/prettier */
const videoLibrary = {

    "0.mp4": require("../../videos/0.mp4"),
    "1.mp4": require("../../videos/1.mp4"),
    "2.mp4": require("../../videos/2.mp4"),
    "3.mp4": require("../../videos/3.mp4"),
    "4.mp4": require("../../videos/4.mp4"),
    "5.mp4": require("../../videos/5.mp4"),
    "6.mp4": require("../../videos/6.mp4"),
    "7.mp4": require("../../videos/7.mp4"),
    "8.mp4": require("../../videos/8.mp4"),
    "9.mp4": require("../../videos/9.mp4"),
    "10.mp4": require("../../videos/10.mp4"),
    "11.mp4": require("../../videos/11.mp4"),
    "12.mp4": require("../../videos/12.mp4"),
    "13.mp4": require("../../videos/13.mp4"),
    "14.mp4": require("../../videos/14.mp4"),
    "15.mp4": require("../../videos/15.mp4"),
    "16.mp4": require("../../videos/16.mp4"),
    "17.mp4": require("../../videos/17.mp4"),
    "18.mp4": require("../../videos/18.mp4"),
    "19.mp4": require("../../videos/19.mp4"),
    "20.mp4": require("../../videos/20.mp4"),
    "hello.mp4": require("../../videos/hello.mp4"),
    "how-are-you.mp4": require("../../videos/how-are-you.mp4"),
    "bye.mp4": require("../../videos/bye.mp4"),
    "i-am.mp4": require("../../videos/i-am.mp4"),
    "i-like.mp4": require("../../videos/i-like.mp4"),
    "good.mp4": require("../../videos/good.mp4"),
    "bad.mp4": require("../../videos/bad.mp4"),
    "yes.mp4": require("../../videos/yes.mp4"),
    "no.mp4": require("../../videos/no.mp4"),
    "who.mp4": require("../../videos/who.mp4"),
    "what.mp4": require("../../videos/what.mp4"),
    "where.mp4": require("../../videos/where.mp4"),
    "when.mp4": require("../../videos/when.mp4"),
    "why.mp4": require("../../videos/why.mp4"),
    "a.mp4": require("../../videos/a.mp4"),
    "b.mp4": require("../../videos/b.mp4"),
    "c.mp4": require("../../videos/c.mp4"),
  };

  export default videoLibrary;